GET https://project-igip.onrender.com/api/expenses

###
GET https://project-igip.onrender.com/api/expenses/12

###
GET https://project-igip.onrender.com/api/expenses/date/2022-11-15

###
GET https://project-igip.onrender.com/api/expenses/cost/157.56

###
GET https://project-igip.onrender.com/api/expenses/category/groceries

###
GET https://project-igip.onrender.com/api/expenses/shop/Lidl

###
POST https://project-igip.onrender.com/api/expenses HTTP/1.1
Content-Type: application/json

{
    "date": "2022-10-21",
    "amount": 123.56,
    "shop": "Prisma",
    "category": "groceries"
}

###
DELETE https://project-igip.onrender.com/api/expenses/7

###
PUT https://project-igip.onrender.com/api/expenses HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "date": "2022-10-15",
    "amount": 157.56,
    "shop": "Mardin",
    "category": "eating out"
}