openapi: 3.0.3
info:
  title: Backend project for following expenses
  version: 1.0.0
  description: |-
    This is a simple backend API for keeping a database on various expenses. 
    The database is hosted on seperate server and deployed by using [Render](https://render.com/).
  contact:
    name: Hilla Hotakainen
    email: hilla.hotakainen@outlook.com
servers:
  - url: https://project-igip.onrender.com/api

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /expenses:
    get:
      description: Returns list of all expenses
      responses:
        "200":
          description: Succesfully returned list of expenses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    date:
                      type: string
                    amount:
                      type: integer
                    shop:
                      type: string
                    category:
                      type: string
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
